package team2679.core.graph;

import team2679.core.spline.SplineWrapper;
import team2679.core.spline.WayPoint;

import java.util.ArrayList;

/**
 * This class generates a graph of the robot's angular speed.
 */
public class AngularSpeedGenerator {

    /**
     * @param spline The robot's path.
     * @param speed A graph of the speeds of the robot generated by MotionProfileGenerator.
     * @return A graph of the angular speed of the robot against distance.
     */
    public IntervalGraph<Double> generate(SplineWrapper spline, IntervalGraph<Double> speed) {
        ArrayList<Double> angularSpeed = new ArrayList<>();
        for (int i = 0; i < speed.list.size(); i++) {
            angularSpeed.add(speed.list.get(i) * spline.getIntervalGraph().list.get(i).curvature);
        }
        return new IntervalGraph<>(angularSpeed, speed.step);
    }

}
